version: '3'
services:
  onion-dns:
    build: .
    image: blackhatch/onion-dns
    restart: always
    container_name: onion-dns
    ports:
      - "5353:53"
    environment:
      - PORT=53
    networks:
      - dns

networks:
  dns:
    driver: "bridge"
