---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: default
data:
 1053: "default/dns:53"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: default
data:
 1053: "default/dns:53"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.29.7
    component: controller
    heritage: Helm
    release: nginx
  name: nginx-nginx-ingress-controller
  namespace: default
spec:
  clusterIP: 10.102.95.197
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30330
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30380
    port: 443
    protocol: TCP
    targetPort: https
  - name: dns
    port: 1053
    targetPort: 1053
    protocol: TCP
  selector:
    app: nginx-ingress
    component: controller
    release: nginx
  sessionAffinity: None
  type: LoadBalancer
