apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    app: dns
  ports:
    - protocol: TCP
      name: tcpdns 
      port: 53 
      targetPort: 53
    - protocol: UDP
      name: udpdns 
      port: 53 
      targetPort: 53
